#!/usr/bin/perl
# Version: 1.0
# Description: A program to test typing speed and accuracy
#

use strict;
use warnings;

use Term::ReadKey;
use Term::ReadLine;
use Time::HiRes qw( time );

use lib 'lib';
require "layouts.pl";
require "wordlists.pl";


# Menu:
my $layout_name = "none";
my $wordlist_file = "new";

my @words;
my $layout;

menu();
# Menu:
# - Start test
#   run test with $layout and $text
# - Select layout
#   choose layout help to display from layouts.json keys and set $layout to the value
#   default to none
# - Select words list
#   choose from lists folder and set $text to the value
#   default to new (new list creation before start on it)
# - Create words list
#   Create randomized words list and set $wordlist to it

sub menu {
    print "\e[2J\e[H"; # Clear screen and move cursor to top-left corner
    print "PERL-TYPING\n\n";
    print "1. Start test\n";
    print "2. Select layout ($layout_name)\n";
    print "3. Select words list ($wordlist_file)\n";
    print "4. Create words list\n";
    print "5. Exit\n";

    ReadMode('cbreak');
    my $key = Term::ReadKey::ReadKey(0);
    ReadMode(0);
    if ($key eq 1) {
        $layout = get_layout($layout_name);
        @words = get_word_list($wordlist_file);
        start_test();
    } elsif ($key eq 2) {
        $layout_name = choose_layout();
        menu();
    } elsif ($key eq 3) {
        $wordlist_file = choose_word_list();
        menu();
    } elsif ($key eq 4) {
        random_creation();
        menu();
    } elsif ($key eq 5 or $key eq "\e") {
        exit;
    } else {
        menu();
    }
}

sub start_test {

    my %char_times;
    my %incorrect_chars;
    my $start_time = 0;
    my $prev_time = $start_time;
    my $total_time = 0;
    my $total_chars = 0;
    my $correct_chars = 0;

    print "\e[2J\e[H";
    if ($layout_name ne "none") {
        print "\e[90m$layout_name\e[0m\n";
    }

    print "*" x 80 . "\n";
    print "*              Press 'esc' anytime to exit and 'tab' to restart.               *\n";
    print "*" x 80 . "\n";    

    # Split the words into lines of 10 words
    my @lines;

    my $n = 0;
    for (my $i = 0; $i < scalar(@words); $i++) {
        if ($i % 10 eq 9) {
            $lines[$n] .= $words[$i];
            $n++;
        } else {
            $lines[$n] .= $words[$i] . " ";
        }
    }

    # Save cursor position
    print "\e[s";
    foreach my $line (@lines) {
        print "$line\n";

    }
    # Restore cursor position
    print "\e[u";

    foreach my $line (@lines) {
        # Prompt the user to type the line
        my $input = '';
        my $char = '';
        my $prev = '';
        for (my $i = 0; $i < length($line); $i++) {
            # Display the character to type
            $char = substr($line, $i, 1);
            if (defined $layout) {
                update_layer($layout, $char, $prev);
                $prev = $char;
            }

            # Prompt the user to type the character
            my $char_input = readChar();
            if ($char_input eq "\e") {
                menu();
            } elsif ($char_input eq "\t") {
                start_test();
            }
            $input .= $char_input;

            # Calculate the time taken to type the character
            if ($start_time eq 0) {
                $start_time = time;
                $prev_time = $start_time;
            }
            my $char_time = time - $prev_time;
            $prev_time = time;

            if (not exists $incorrect_chars{$char}) {
                $incorrect_chars{$char} = 0;
            }
            if ($char eq $char_input) {
                if (exists $char_times{$char}) {
                    push @{$char_times{$char}}, $char_time;
                } else {
                    $char_times{$char} = [$char_time];
                }
                # Display the character in green
                print "\e[32m$char\e[0m";
            } else {
                # Add the character to the list of incorrect characters
                $incorrect_chars{$char}++;
                # Display the character in red
                print "\e[31m$char_input\e[0m";
            }

            # Count the number of characters
            $total_chars++;

            # Count the number of correct characters
            if ($char eq $char_input) {
                $correct_chars++;
            }
        }
        # Wait for the user to press enter
        my $key = readChar();
        if ($key eq "\n") {
            print "\e[1E\e[1G";
        } else {
            print "\e[31m█\e[0m\e[1E\e[1G";
        }
    }
    
    my $cpm = 60 * ($total_chars / (time - $start_time));

    print  "\n" . "-" x 80 . "\n";
    printf "Time: %.2f seconds\n", time - $start_time;
    printf "Speed: %.2f CPM\n", $cpm;
    printf "Speed: %.2f WPM\n", 60 * (scalar(@words) / (time - $start_time));
    print  "-" x 80 . "\n";
    printf "Errors: %s\n", $total_chars - $correct_chars;
    printf "Accuracy: %.2f%%\n", 100 * ($correct_chars / $total_chars);
    print  "-" x 80 . "\n";
    # Display the results
    $n = 0;
    foreach my $char (sort keys %char_times) {
        my $char_avg_time = sprintf("%.2f", average(@{$char_times{$char}}));
        my $char_accuracy = sprintf("%.2f", 100 * (1 - ($incorrect_chars{$char} /
            (scalar(@{$char_times{$char}}) + $incorrect_chars{$char}))));

        my $char_cpm = 0;
        if ($char_avg_time ne '0.00') {
            $char_cpm = 60 / $char_avg_time;
        }
        if ($char_accuracy eq '100.00') {
            if ($char_cpm gt $cpm) {
                print "\e[92m";
            } else {
                print "\e[93m";
            }
        } else {
            print "\e[91m";
        }

        printf "%s: %.3s CPM (%s%%)", $char, $char_cpm, $char_accuracy;
        print "\e[0m";

        if ($n % 3 == 0) {
            print "\n";
        } else {
            print "\t";
        }
        $n++;
    }
    print  "\n" . "-" x 80 . "\n";
    # Restart or return to main menu
    print "Press 'tab' to restart or 'esc' to return to main menu.\n";
    my $key;
    do {
        ReadMode('cbreak');
        $key = Term::ReadKey::ReadKey(0);
        ReadMode(0);

        if ($key eq '\t') {
            start_test();
        } elsif ($key eq '\e') {
            menu();
        }
    } while ($key ne '\t' and $key ne '\e');
}


# Function to calculate the average of a list of numbers
sub average {
    my $total = 0;
    foreach my $number (@_) {
        $total += $number;
    }
    return $total / scalar(@_);
}

# Function
sub readChar {
    ReadMode('cbreak');
    my $key = Term::ReadKey::ReadKey(0);
    ReadMode(0);
    return $key;
}

